[package]
name = "gust"
version = "0.1.0"
edition = "2018"

[dependencies]
rust-crypto = "0.2.36"
hex = "0.4.3"
deflate = "1.0.0"
flate2 = "1.0.22"
bstr = "1.0.1"
anyhow = "1.0.66"
thiserror = "1.0.37"
spdlog-rs = "0.3.7"
byteorder = "1.4.3"
sha-1 = "0.10.1"
imara-diff = "0.1.5"
min-max = "0.1"
colored= "2.0.0"
crc = "3.0.0"
diffs ="0.4.1"